"use client";

import { motion } from "framer-motion";
import { Quote } from "lucide-react";
import { DataHubDiagram } from "@/components/diagrams/DataHubDiagram";

export default function AboutPage() {
  return (
    <div className="container mx-auto px-4 py-24 space-y-24">
      {/* Intro Section */}
      <section className="max-w-4xl mx-auto text-center space-y-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <h1 className="text-4xl md:text-6xl font-bold tracking-tight mb-6">
            Pioneering Generative <br />
            <span className="text-primary/80">Autonomous Intelligence</span>
          </h1>
          <p className="text-xl text-muted-foreground leading-relaxed">
            Auwomo is a commercialization spin-off from the Autonomous Intelligence Lab at Westlake University. We are dedicated to building the generative infrastructure that powers the next generation of autonomous driving.
          </p>
        </motion.div>
      </section>

      {/* Mission Section */}
      <section className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          className="space-y-6"
        >
          <h2 className="text-3xl font-bold">Our Mission</h2>
          <div className="h-1 w-20 bg-accent rounded-full" />
          <p className="text-lg text-muted-foreground">
            To build the Generative Scale AI for the physical world. We believe that the key to unlocking true Level 5 autonomy lies not just in better algorithms, but in better data—specifically, high-fidelity, physically accurate synthetic data generated by World Models.
          </p>
          <p className="text-lg text-muted-foreground">
            By bridging the gap between simulation and reality, we enable AI systems to learn from infinite scenarios, including the critical "long-tail" edge cases that are impossible to capture at scale in the real world.
          </p>
        </motion.div>

        <div className="w-full flex justify-center lg:justify-end min-h-[500px]">
          <DataHubDiagram />
        </div>
      </section>

      {/* Lab Background */}
      <section className="bg-secondary/5 rounded-2xl p-8 md:p-16 border border-border/50">
        <div className="max-w-3xl mx-auto text-center space-y-8">
          <Quote className="w-12 h-12 text-primary/20 mx-auto" />
          <h2 className="text-2xl md:text-3xl font-bold">Rooted in Academic Excellence</h2>
          <p className="text-lg text-muted-foreground">
            Founded at the School of Engineering, Westlake University, our team combines rigorous academic research with fast-paced industrial application. Our core technology stems from years of top-tier research in computer vision, neural rendering, and autonomous systems.
          </p>
        </div>
      </section>

    </div>
  );
}

